/* 外贸领航者 · 共享脚本
 * 提供图标、Tailwind 全局配置、公共组件、共享数据。
 * 由 index.html / level1.html / level2.html / level3.html 共同引用。
 */

/* ---------- Tailwind config ---------- */
window.tailwind && (window.tailwind.config = {
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        serif: ['Noto Serif SC', 'ui-serif', 'Georgia', 'serif'],
      },
      colors: {
        ink: {
          950: '#050a14', 900: '#0a1428', 800: '#0f1e3a', 700: '#1a2f52', 600: '#2a4470', 500: '#3d5a8e',
        },
        gold: {
          50:'#fbf7ea', 100:'#f6ecc5', 200:'#edd88a', 300:'#e1c159', 400:'#d4af37', 500:'#b8952e', 600:'#8f7223', 700:'#5f4c17',
        },
        cream: { 50:'#faf9f5', 100:'#f4f1e8', 200:'#e8e2d0' },
      },
      boxShadow: {
        'gold-glow': '0 0 40px -10px rgba(212, 175, 55, 0.45)',
        'ink-elevate': '0 30px 80px -30px rgba(5, 10, 20, 0.55)',
      },
      backgroundImage: {
        'gradient-ink': 'linear-gradient(135deg, #050a14 0%, #0f1e3a 50%, #1a2f52 100%)',
        'gradient-radial-gold': 'radial-gradient(ellipse at center, rgba(212,175,55,0.15) 0%, transparent 60%)',
        'gradient-hero': 'linear-gradient(180deg, #050a14 0%, #0a1428 40%, #0f1e3a 100%)',
      },
      animation: {
        'fade-up': 'fadeUp 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-in': 'fadeIn 1.2s ease-out',
        'pulse-slow': 'pulseSlow 4s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 3s linear infinite',
      },
      keyframes: {
        fadeUp: { '0%': { opacity: 0, transform: 'translateY(24px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        fadeIn: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        pulseSlow: { '0%,100%': { opacity: 0.6 }, '50%': { opacity: 1 } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
    },
  },
});

/* ---------- Shared tier data ---------- */
window.TIER_DATA = {
  l1: {
    id: 'l1',
    tier: 'LEVEL 01',
    title: '小白支持站',
    subtitle: '活下来',
    tag: '入行 0 – 6 个月',
    accentHex: '#10b981',
    accentSoft: 'rgba(16, 185, 129, 0.12)',
    accentSoftStrong: 'rgba(16, 185, 129, 0.22)',
    stat: { modules: 6, hours: 28, lessons: 42 },
    description: '入行第一步。这里没有高深理论，只有可复制的动作：从看懂第一封询盘开始，到独立跑完第一笔订单结束。',
    outcome: '4 周内能独立处理询盘、写出合格开发信、跟完一笔完整订单。',
    pedagogy: '721 学习法：70% 实战 + 20% 反馈 + 10% 课程；配合影子跟单与刻意练习',
    modules: [
      {
        name: '外贸行业认知',
        desc: '先搞清楚这是个什么行业、能赚多少钱、要付出什么',
        points: ['行业全景与真实收入曲线（0-1年/1-3年/3-5年/5年+）','岗位分工全景图（业务/运营/跟单/单证/采购）','是否适合做外贸？性格特质自测','数字化、AI化、品牌出海三大趋势'],
        methodology: [
          '全景地图法：画出「工厂→货代→银行→海关→客户」全链路再深挖节点',
          '案例反推法：拿真实成交订单倒推每个环节的角色与单据',
          '对标学习：每周精读 1 篇 Mike / 毅冰 / 料神的行业复盘长文',
          '术语卡片：把 Incoterms、HS Code、L/C 等 50 个术语做成 Anki 卡',
          'STP 行业调研：Segment（品类）→ Target（市场）→ Positioning（定位）',
        ],
        steps: [
          '认知：3 天读完《外贸大掌柜》+ 橙点同学「必修课」建立全景',
          '模仿：用海关数据/Trademap 拉自家产品出口 Top10 国家榜单',
          '拆解：画 A3 纸「一笔订单 20 动作 + 单据 + 责任方」流程图',
          '实操：跟老业务员影子跟单 1 笔完整订单并做批注',
          '输出：写 1500 字《我司产品的全球市场地图》交主管点评',
          '复盘：每周日回顾新术语与角色关系，更新到个人 wiki',
        ],
      },
      {
        name: '入职30天生存指南',
        desc: '每天知道该干什么，不再无所适从',
        points: ['W1：熟悉公司与产品线（快速吃透产品）','W2：掌握基础工具（邮箱/CRM/平台/WhatsApp）','W3：看懂询盘与回复（分类 + 模板）','W4：跟着老人跑一单（影子学习法）','每日 SOP 时间表：早-中-晚该做什么'],
        methodology: [
          'PDCA 日清法：每晚 15 分钟列次日 3 件最重要事',
          '5W2H 提问模板：请教老同事前先自答一遍再问',
          '反焦虑生存法：不比开单，只比周同比动作量',
          '工位 SOP 化：邮箱签名 / 报价模板 / 跟进表 3 天内定型',
          '1-3-7 汇报节奏：第 1、3、7 天主动跟主管对齐目标',
        ],
        steps: [
          '认知：第 1 天读透公司产品册、价格体系、返点政策',
          '融入：第 3 天前认全同事+外部合作方（货代/QC/单证/财务）',
          '模仿：抄写 30 封老业务往来邮件，标注句式和潜台词',
          '实操：第 2 周开始独立回复非报价类询盘，主管审核后再发',
          '工具：配置 CRM + 邮箱标签 + 谷歌日历跟进提醒',
          '复盘：30 天末交《试用期学习地图》：会了什么、卡在哪',
        ],
      },
      {
        name: '商务英语速成',
        desc: '不追求文学水平，追求让老外看懂',
        points: ['邮件写作四段式公式（开场/正文/CTA/签名）','50 个高频场景邮件模板一键复制','FOB/CIF/MOQ/OEM/ODM 术语速查表','电话/视频会议基本话术'],
        methodology: [
          '场景化学习：按「询盘/砍价/催款/投诉」4 大场景背句式',
          '邮件三段式：Purpose→Detail→Call-to-Action，每封≤150 词',
          '影子跟读：每天 20 分钟跟读 BBC Business / CNBC 财经',
          '术语对照：Incoterms + 单证 + 支付 3 张卡各 50 词',
          'AI 陪练：用 ChatGPT / 豆包 role-play 每天 15 分钟',
        ],
        steps: [
          '认知：1 周内看完汪晟开发课语感篇 + 毅冰《一天一封开发信》',
          '输入：整理 100 句「万能商务句式」按场景归档到石墨文档',
          '模仿：每天仿写 1 封真实客户邮件，Grammarly 打分 ≥90',
          '开口：每周 2 次与同事 15 分钟英文 role-play 询价/砍价',
          '实战：独立处理 5 封往来邮件，主管批注错点再改写归档',
          '复盘：月末录 3 分钟产品介绍视频对比首周基线',
        ],
      },
      {
        name: '订单全流程实操',
        desc: '一笔订单从头到尾的 12 步',
        points: ['12 步生命周期地图（询盘 → 收款）','询盘分析与报价计算（成本核算 + 利润率）','PI 与合同制作模板','付款方式入门：T/T / L/C / D/P 初识','出口单证基础（发票/装箱单/提单/CO）'],
        methodology: [
          '单据驱动法：以 10 张核心单据串起全流程',
          '价格拆解法：报价先做 FOB 成本表（料+工+费+利+汇率 buffer 2-3%）',
          '节点提醒法：CRM 里给每笔单设 8 个关键节点自动提醒',
          '预警清单：每笔单进入生产前过一遍「12 项风险自检表」',
          '复盘归档：每笔单结案后写 1 页「利润+问题+改进」',
        ],
        steps: [
          '认知：吃透 Incoterms 2020 中 EXW/FOB/CIF/DDP 5 种常用条款',
          '拆解：把公司近 3 笔真实订单所有单据打印按时间线贴墙',
          '模仿：用模板独立做 3 份 PI、3 份 SC 合同，主管红笔批改',
          '工具：在 OKKI/小满里跑通 1 笔完整商机看板（询盘→回款）',
          '实操：主导 1 笔小额订单（<5 万美金），全流程责任到自己',
          '复盘：结案后填订单复盘表，在周会 5 分钟分享踩坑点',
        ],
      },
      {
        name: '客户开发入门',
        desc: '找到人、加上好友、开口聊',
        points: ['客户画像基础（终端/批发/零售/电商）','B2B 平台基础操作（阿里 / 中国制造网）','Google 高级搜索 20 条指令','LinkedIn Profile 优化 + 加人话术','开发信标题公式与首封回复率优化'],
        methodology: [
          '料神三板斧：关键词分层 → 高级搜索指令 → 决策人挖掘',
          'Google 20 指令：site: intitle: inurl: filetype: 组合精准定位',
          '领英三步开发：加人话术模板 → 内容种草 → InMail 转私域',
          '海关数据反查：用腾道按 HS Code 拉出口商挖真实买家',
          'P4P 漏斗复盘：每周看曝光/点击/反馈调整关键词与主图',
        ],
        steps: [
          '认知：1 周内学完橙点同学「运营必修课」+ 料神免费公开课',
          '建模：为主打 2 个产品各建 30 个精准关键词',
          '实操 A：Google site:.com + 关键词找 30 个客户官网',
          '实操 B：LinkedIn 每天加 20 个精准决策人，发定制开场白',
          '实操 C：海关数据筛 50 家近 6 个月活跃采购商',
          '复盘：每周统计触达/回复/询盘转化率，淘汰低效渠道',
        ],
      },
      {
        name: '新手避坑指南',
        desc: '别用真金白银交学费',
        points: ['20 个新手常犯错误 + 解决方案','付款方式风险等级图（从安全到危险）','尼日利亚骗局 / 钓鱼邮件 / 假水单识别','汇率基础常识（报价 buffer 逻辑）','什么时候该问老板 / 什么时候自己能定'],
        methodology: [
          'KYC 三查法：查公司注册（Dun&Bradstreet）+ 网站备案 + IP 归属',
          '付款优先级：T/T 30+70 > L/C at sight > D/P > D/A > O/A',
          '汇率 buffer 法：报价锁 2-3% 缓冲 + 大单远期结汇',
          '红旗清单：8 大骗局特征（改抬头、假支票、超低价、催 SWIFT 截图）',
          '分权保护：印章/合同/收款账号三权分立，变更必打确认电话',
        ],
        steps: [
          '认知：读完 XTransfer《外贸骗局白皮书》+ 商务部预警',
          '建库：整理 20 个真实骗局案例做「反面教材卡片」贴工位',
          '工具：装信保 / XTransfer / PingPong 学会看风控评分',
          '演练：模拟 3 个骗局场景（换账号、L/C 软条款、假水单）',
          '汇率：用银行远期结汇工具做一次 5 万美金模拟锁汇',
          '复盘：每月与财务对一次汇兑损益，反推 buffer 是否合理',
        ],
      },
    ],
    weeks: [
      {
        w: 'Week 1',
        theme: '行业破冰 + 工位就绪：3 天看懂外贸，7 天融入团队',
        tasks: ['公司主营 & 目标市场','产品线 SKU / 参数熟悉','工厂参观 / 工艺理解','产品 FAQ 20 题清单'],
        lessons: [
          { no: '1-1', title: '外贸产业链全景图：从工厂到终端消费者的 12 个角色', min: 30 },
          { no: '1-2', title: 'Incoterms 2020 五大常用条款拆解（EXW/FOB/CIF/CFR/DDP）', min: 35 },
          { no: '1-3', title: '公司产品册精读法：3 小时读透 100 页目录的 SQ3R 技巧', min: 25 },
          { no: '1-4', title: '外贸单据地图：10 张核心单据的样板与用途逐张认脸', min: 40 },
          { no: '1-5', title: '工位 SOP：邮箱签名 / 报价模板 / 跟进表 30 分钟搭好', min: 30 },
          { no: '1-6', title: '阿里国际站后台 6 大模块走查（数据/RFQ/P4P/信保）', min: 35 },
          { no: '1-7', title: '老业务影子跟单：一天贴身观察记录 20 个动作', min: 40 },
        ],
        homework: [
          '画一张 A3《外贸全流程 20 节点图》并标注每个节点单据与责任方',
          '整理 50 个外贸高频术语的中英对照 Excel 表并录入 Anki',
          '复盘 1 笔公司真实历史订单，写 500 字「这笔单为什么能成」',
          '把工位邮箱、CRM、跟进表 3 件套配好并截图给 mentor 验收',
        ],
        deliverable: '《我的第 1 周行业认知手册》：全流程图 + 术语表 + 1 笔订单复盘',
      },
      {
        w: 'Week 2',
        theme: '商务英语实战 + 邮件写作：从抄写到独立回复询盘',
        tasks: ['公司邮箱 & 签名档设置','CRM 系统操作 & 客户建档','B2B 平台后台熟悉','WhatsApp / Skype / 领英账号'],
        lessons: [
          { no: '2-1', title: '开发信三段式：Hook-Value-CTA 拆解 10 封高回复邮件', min: 35 },
          { no: '2-2', title: '询盘 5 类分级法（垃圾/试探/比价/真实/紧急）差异化回复', min: 30 },
          { no: '2-3', title: '报价邮件 8 要素：不给客户「再找我」的理由', min: 30 },
          { no: '2-4', title: '商务英语砍价话术 20 句：How can we work this out?', min: 25 },
          { no: '2-5', title: '催款催样催 PI 三大催收邮件的语气梯度', min: 30 },
          { no: '2-6', title: '投诉与索赔邮件：让客户消气又不让公司担责的写法', min: 35 },
          { no: '2-7', title: 'ChatGPT/豆包 Role-play：模拟印度买家砍价 15 分钟', min: 40 },
          { no: '2-8', title: '语音 & 视频会议 10 大破冰句 + 常见误听词纠正', min: 30 },
        ],
        homework: [
          '仿写 5 封真实场景邮件（询盘/报价/砍价/催款/投诉）Grammarly 得分 ≥90',
          '录制一段 3 分钟英文产品介绍视频，用剪映加中英字幕',
          '整理 100 句「万能商务句式」按 8 大场景归类到石墨文档',
          '与同事完成 2 次 role-play，录音回听并写反思 300 字',
          '独立回复 3 封真实非报价类询盘（主管审后发出）',
        ],
        deliverable: '《个人邮件模板库 V1.0》：8 场景 × 3 版本共 24 个模板 + 1 段自我介绍视频',
      },
      {
        w: 'Week 3',
        theme: '客户开发实战：Google + LinkedIn + 海关数据组合拳',
        tasks: ['询盘分类（真/假/试探/竞品）','8 种场景回复模板','首次报价的 5 大要素','跟进节奏：D+1 / D+3 / D+7'],
        lessons: [
          { no: '3-1', title: '关键词金字塔：产品词/场景词/人群词/长尾词 4 层建模', min: 35 },
          { no: '3-2', title: 'Google 高级搜索 20 条指令实战（site: intitle: inurl: filetype:）', min: 40 },
          { no: '3-3', title: '料神精准客户开发：从官网挖出采购决策人 Email 的 6 步', min: 40 },
          { no: '3-4', title: 'LinkedIn 个人档案打造 8 要素：让客户主动加你', min: 30 },
          { no: '3-5', title: 'LinkedIn 每日 20 加人 SOP + 首条消息 3 版话术', min: 30 },
          { no: '3-6', title: '海关数据实操：腾道/贸易宝按 HS Code 拉活跃买家名单', min: 35 },
          { no: '3-7', title: '阿里国际站 RFQ 抓取 + P4P 关键词工具使用', min: 30 },
          { no: '3-8', title: '客户 KYC 三查：Dun&Bradstreet + IP 反查 + 领英验证', min: 30 },
        ],
        homework: [
          '用 site: + 产品关键词找到 30 个目标客户官网并整理成 Excel',
          '在 LinkedIn 加 100 个精准决策人，附定制化开场白，记录接受率',
          '海关数据筛 50 家近 6 个月有采购记录的买家并按频次排序',
          '对 30 家客户发送第 1 封开发信，24 小时后统计打开/回复率',
          '为 3 家最优质客户各建 1 张「客户画像卡」',
        ],
        deliverable: '《我的第 1 个 100 家精准客户库》：Excel + 30 封已发开发信 + 3 张深度画像卡',
      },
      {
        w: 'Week 4',
        theme: '订单全流程闭环 + 避坑毕业：主导一笔真实小单',
        tasks: ['影子跟单一笔完整订单','PI 与合同实战填写','验货 / 报关 / 出运协作','收款与售后跟进'],
        lessons: [
          { no: '4-1', title: '报价成本表搭建：料+工+费+利+汇率 buffer 5 项 Excel 公式', min: 40 },
          { no: '4-2', title: 'PI / SC 合同 8 大条款逐项审阅（品名/数量/唛头/交期/罚则）', min: 40 },
          { no: '4-3', title: 'T/T 30-70 vs L/C at sight 收款方式选型决策树', min: 30 },
          { no: '4-4', title: '生产节点管控：QC 三查 + 大货前样确认防雷', min: 30 },
          { no: '4-5', title: '报关单据链：Invoice/Packing/B/L/CO/FORM E 出错点大全', min: 35 },
          { no: '4-6', title: '外贸 8 大骗局识别：改抬头 / 软条款 L/C / 假水单 / 超低价', min: 35 },
          { no: '4-7', title: '汇率 buffer 与远期结汇：小单 2-3% 缓冲，大单锁汇实操', min: 30 },
          { no: '4-8', title: '订单复盘模板：利润 / 问题 / 改进 / 客户升级 4 象限', min: 25 },
        ],
        homework: [
          '独立完成 1 份 PI + 1 份 SC 合同，主管红笔批改后 V2 定稿',
          '为 1 笔询盘做完整报价（含成本表 + 3 档阶梯价 + 汇率 buffer）',
          '整理 20 个真实骗局案例做 A4「反面教材墙报」贴工位',
          '用 XTransfer/信保后台模拟 1 次 5 万美金收款并解读风控评分',
          '主导（或深度陪跑）1 笔真实小额订单从询盘走到 PI 签约',
        ],
        deliverable: '毕业作品《一笔小单全流程作战包》：报价成本表 + PI/SC 合同 + 客户 KYC 报告 + 20 骗局清单 + 订单复盘 1 页纸，毕业答辩会 10 分钟路演',
      },
    ],
    tools: ['阿里国际站','中国制造网','Gmail','Outlook','WhatsApp Business','钉钉外贸版','谷歌翻译','Grammarly'],
    graduation: {
      hard: [
        '客户库 ≥100 家精准目标客户（Excel 归档）',
        '已发送开发信 ≥50 封，回复率 ≥3%',
        '独立完成 ≥1 份合规 PI 与合同',
        '英文邮件 Grammarly 平均分 ≥90',
        '识别至少 8 类外贸骗局并能口述反诈流程',
      ],
      soft: [
        '能用英文 15 分钟无卡顿介绍公司与产品',
        '能独立与货代/QC/单证/财务四方协作推动订单',
        '能对老业务的一封开发信提出 3 条以上改进建议',
        '工位 SOP、CRM、跟进表三件套稳定运转 4 周以上',
      ],
    },
    faq: [
      { q: '完全零基础，英语只有四级，能做外贸吗？', a: '能。外贸邮件用词非常固定，掌握 200 个高频短语 + 会用 Grammarly，写出得体邮件完全没问题。但你必须保持每天进步的节奏。' },
      { q: '入职多久没出单是不是就要被开了？', a: '外贸行业普遍容忍度是 3-6 个月。前 3 个月是「学习期」，能拿基本工资；4-6 个月要有活跃客户和意向订单；6 个月还没首单，需要认真复盘方法论。' },
      { q: '产品完全不懂，客户问技术参数怎么办？', a: '第一原则：不要瞎答。诚实说 let me confirm with our engineer and get back to you within 24 hours，然后立刻去问技术。回复速度和准确性比装懂重要一万倍。' },
      { q: '公司平台账号没有，该怎么开始找客户？', a: 'Google 高级搜索 + LinkedIn 免费搜索 + 展会官网参展商名单 + 海关数据免费试用版，这四件事就够你忙 3 个月了。' },
    ],
    sources: ['阿里国际站橙点同学','料神米课','汪晟米课开发课','OKKI 小满','连连国际','腾道数据','XTransfer 风控专栏','HKTDC Digital Academy','毅冰米课','知乎外贸新人话题'],
  },

  l2: {
    id: 'l2',
    tier: 'LEVEL 02',
    title: '新手成长营',
    subtitle: '站住脚',
    tag: '入行 6 个月 – 2 年',
    accentHex: '#0ea5e9',
    accentSoft: 'rgba(14, 165, 233, 0.12)',
    accentSoftStrong: 'rgba(14, 165, 233, 0.22)',
    stat: { modules: 6, hours: 56, lessons: 78 },
    description: '有过第一单之后，真正的挑战开始。你要建立稳定的客户群、把出单变成可控的节奏。三大战场并行：B2B 平台 × 独立站 × 社媒。',
    outcome: '8 周内开发出 3+ 有效客户，独立站上线，首篇 SEO 内容产出。',
    pedagogy: 'MECE 客户开发漏斗 + A/B 测试实验 + 关键词金字塔 + 谈判 BATNA',
    modules: [
      {
        name: '客户开发进阶',
        desc: '从广撒网到精准打击',
        points: ['海关数据深度挖掘（采购频次 / 供应商变动 / 价格趋势）','LinkedIn Sales Navigator 高级筛选','开发信 A/B 测试体系（标题 / 正文 / CTA / 时段）','Google Maps + 黄页地毯式开发','客户 CRM 系统搭建（从 Excel 升级）','展会 7 天跟进法'],
        methodology: [
          'MECE 客户开发漏斗：分层筛选目标 ICP',
          '海关数据反查买家 + 竞品供应链路',
          'LinkedIn Sales Nav 布尔搜索 + InMail 触达',
          '开发信标题 / 正文 / CTA 三段 A/B 测试',
          'CRM 分级打标 + 7 触点自动化跟进',
        ],
        steps: [
          '定义 ICP 画像：行业 / 规模 / 地区 / 采购角色',
          '搭建渠道矩阵：海关+领英+Google+展会名录',
          '建立客户池并按 A/B/C 三级打分排序',
          '首轮开发信 A/B 测试标题、CTA 与发送时段',
          '配置 CRM 标签、任务与 7 步跟进 SOP',
          '每周复盘打开率、回复率、约会率数据',
        ],
      },
      {
        name: 'B2B 平台深度运营',
        desc: '把平台流量榨干',
        points: ['阿里国际站数据纵横每个指标解读','P4P 直通车投放策略（选词/出价/时段/预算）','RFQ 高效抢单：什么值得抢 + 怎么写','关键词研究三结合方法','产品详情页优化（标题公式 / 主图 / 视频）','店铺评分与信用体系维护','TOP10 竞品分析框架'],
        methodology: [
          '数据纵横反推行业蓝海词与流量缺口',
          'P4P 分层出价：核心词+精准+长尾组合',
          '详情页 FABE 结构 + 首屏黄金 3 秒法则',
          'RFQ 24 小时首响 + 差异化报价模板',
          '星等级 / 橱窗 / 主图三维打分周迭代',
        ],
        steps: [
          '诊断店铺健康分、信保额度与曝光基线',
          '构建行业词库：热度 / 竞争度 / 转化三维筛词',
          '拆分 P4P 计划：核心 / 精准 / 广泛三级预算',
          '重写详情页 FABE + 短视频 + A+ 图文模块',
          '每日 3 条 RFQ 精准报价并跟进闭环',
          '周报追踪曝光→点击→询盘→成交漏斗',
        ],
      },
      {
        name: '独立站建设与 SEO',
        desc: '把流量装进自己的口袋',
        points: ['WordPress + WooCommerce / Shopify 选型','域名策略与品牌命名','On-Page / Off-Page / Technical SEO','关键词攻占路径：长尾 → 核心','内容营销（博客 / 产品页 / Case Study）','Google Ads 基础（Search / Display / RMK）','GA4 安装与核心报表'],
        methodology: [
          '关键词金字塔：品牌词 / 品类词 / 长尾词',
          'On-Page SEO：TDK + H1 + Alt + 内链结构',
          'Off-Page：Guest Post + 资源页 + HARO 外链',
          'E-E-A-T 内容集群 + 主题聚合页策略',
          'Core Web Vitals 与移动端体验优化',
        ],
        steps: [
          '选型 WP / Shopify，配置域名 / 主机 / 主题',
          '用 Ahrefs / SEMrush 建关键词金字塔词库',
          '搭建首页 / 品类 / 产品 / 博客四层信息架构',
          '技术 SEO：sitemap / schema / 速度 / HTTPS',
          '执行 Skyscraper + 客座博客 + 资源页外链',
          '月度追踪自然流量、排名与询盘转化率',
        ],
      },
      {
        name: '商务谈判与沟通',
        desc: '价格谈判不再心虚',
        points: ['阶梯 / 组合 / 价值三种报价策略','谈判心理学（锚定 / 损失厌恶 / 互惠）','8 种降价应对话术','跨文化沟通：欧美 / 中东 / 东南亚 / 南美 / 非洲','24 小时全球客户触达节奏','客户来访接待 SOP'],
        methodology: [
          'BATNA 底线 + ZOPA 议价区间设定',
          '阶梯报价 + 锚定效应主导议题',
          '降价条件交换：数量 / 账期 / 预付 / 独家',
          'Hofstede 跨文化维度识别沟通风格',
          '客户接待 5 天 SOP + FAQ 应答库',
        ],
        steps: [
          '梳理客户画像与采购决策链角色',
          '设计三档报价：底价 / 目标价 / 挂牌价',
          '演练 10 大降价话术与拒绝话术剧本',
          '邮件 / 电话 / 视频会议分场景模板化',
          '制定验厂接待 5 天动线与议程 SOP',
          '谈判录音复盘 + 胜率与降幅数据分析',
        ],
      },
      {
        name: '供应链与物流管理',
        desc: '把订单交出去也是本事',
        points: ['供应商找 / 验 / 谈 / 管四步法','验货标准与 AQL 抽检','FOB / CIF 责任划分','HS 编码归类与常见退单原因','出口退税免抵退 vs 免退税','货运保险险种与理赔'],
        methodology: [
          '供应商三级分层 + 双源备份策略',
          'AQL 2.5 / 4.0 抽样验货标准',
          'Incoterms 2020 报价成本精算',
          '出口退税：单证 + 函调 + 备案闭环',
          '物流选型：FCL / LCL / 空运 / 中欧班列',
        ],
        steps: [
          '建立供应商资质档案与准入评分',
          '制定 QC 计划：中期 + 尾期 + 装柜三查',
          '搭建 FOB / CIF / DDP 成本核算模板',
          '打通报关、退税、收汇全流程闭环',
          '配置 ICC(A) 保险方案与索赔 SOP',
          '月度评估交期、良率、成本三大 KPI',
        ],
      },
      {
        name: '风险管理与合规',
        desc: '别把订单做成教训',
        points: ['合同关键条款逐条解读','信用证审证要点与软条款识别','贸易纠纷升级路径（协商→仲裁→诉讼）','CE / FDA / REACH / RoHS / BSCI 认证','知识产权防护','汇率风险管理实操（远期结汇 / buffer）'],
        methodology: [
          'UCP600 信用证 5C 审证清单',
          '认证矩阵：目标国 × 品类合规映射',
          '汇率对冲：远期结售汇 / 期权 / NDF',
          '客户 KYC + 邓白氏信用调查',
          '反倾销 + 制裁清单 + 原产地合规',
        ],
        steps: [
          '编制目标市场合规与关税地图',
          'L/C 审证 12 条 checklist + 改证函模板',
          '建立客户 KYC 档案与信用额度制度',
          '测算汇率敞口并设定锁汇比例',
          '启动 CE / FDA / REACH / RoHS 送检备案',
          '每季度合规审计 + 法规更新周报',
        ],
      },
    ],
    weeks: [
      {
        w: 'Week 1-2',
        theme: '外贸认知重塑与客户画像基本功',
        tasks: ['海关数据实战','LinkedIn Sales Nav','开发信 A/B 测试','展会 / 黄页 / Maps'],
        lessons: [
          { no: 'W1-2·1', title: '外贸全流程地图：从询盘到收汇 21 个节点', min: 35 },
          { no: 'W1-2·2', title: '读懂 HS Code 与目标市场关税查询实操', min: 30 },
          { no: 'W1-2·3', title: 'ICP 客户画像五维模型：行业 / 规模 / 地区 / 角色 / 痛点', min: 35 },
          { no: 'W1-2·4', title: '海关数据入门：Panjiva / ImportGenius / 腾道演示', min: 40 },
          { no: 'W1-2·5', title: 'LinkedIn 个人品牌搭建 + Sales Nav 布尔搜索', min: 35 },
          { no: 'W1-2·6', title: 'Google 高级搜索指令 20 个（inurl / intext / filetype）', min: 30 },
          { no: 'W1-2·7', title: '开发信基础框架：AIDA + PAS 结构拆解', min: 35 },
          { no: 'W1-2·8', title: 'CRM 选型对比：Zoho / OKKI / HubSpot 建账实操', min: 30 },
        ],
        homework: [
          '输出本人产品的 ICP 画像文档（3 类客户 + 痛点表）',
          '用海关数据 + 领英交叉验证 20 家目标客户名单',
          '优化 LinkedIn 个人主页并加 50 位精准好友',
          '撰写 3 版开发信模板（AIDA / PAS / 故事型）',
          '搭建 CRM 客户库并完成 A/B/C 分级打标',
        ],
        deliverable: '客户名单 ≥100 家、领英连接 ≥50、CRM 分级完成度 100%、开发信模板通过导师评审',
      },
      {
        w: 'Week 3',
        theme: '客户开发进阶：多渠道触达与 A/B 测试',
        tasks: ['数据纵横诊断','P4P 投放优化','RFQ 抢单实战','详情页升级'],
        lessons: [
          { no: '3-1', title: '海关数据深挖：反查竞品 Top10 买家链路', min: 35 },
          { no: '3-2', title: 'LinkedIn Sales Navigator 高阶用法：Lead List + Alerts', min: 35 },
          { no: '3-3', title: '开发信 A/B 测试实验设计（样本量 / 变量 / 显著性）', min: 40 },
          { no: '3-4', title: '邮件送达率优化：SPF / DKIM / DMARC 配置', min: 30 },
          { no: '3-5', title: '冷邮件工具实操：Mailshake / Woodpecker / Instantly', min: 35 },
          { no: '3-6', title: 'WhatsApp / Skype / Zoom 破冰话术与合规红线', min: 30 },
          { no: '3-7', title: '7 触点跟进节奏 SOP：D1 / D3 / D7 / D14 / D30', min: 30 },
          { no: '3-8', title: '复盘周会模板：漏斗数据 + 胜负案例拆解', min: 25 },
        ],
        homework: [
          '完成 200 封开发信 A/B 测试并出数据分析报告',
          '领英添加 100 位决策人 + 发出 20 封 InMail',
          '录制 3 分钟视频开发信并投递 30 个客户',
          '搭建冷邮件工具 + 完成邮箱认证配置',
          '输出本周漏斗仪表盘：发送 → 打开 → 回复 → 约会',
        ],
        deliverable: '打开率 ≥40%、回复率 ≥8%、有效约会 ≥3 个、邮件送达率 ≥95%',
      },
      {
        w: 'Week 4',
        theme: '阿里国际站深度运营：数据纵横到 P4P',
        tasks: ['Shopify / WP 建站','关键词研究','首篇 SEO 内容','GA4 安装'],
        lessons: [
          { no: '4-1', title: '数据纵横六大模块：市场 / 买家 / 竞对 / 词 / 品 / 店', min: 40 },
          { no: '4-2', title: '行业蓝海词挖掘：搜索热度 × 供需比 × 转化指数', min: 35 },
          { no: '4-3', title: '产品发布 5A 法则：主图 / 属性 / 关键词 / 详情 / 视频', min: 40 },
          { no: '4-4', title: '详情页 FABE + A+ 首屏改造实战', min: 35 },
          { no: '4-5', title: 'P4P 计划搭建：核心词 / 精准长尾 / 否词库', min: 35 },
          { no: '4-6', title: 'RFQ 高转化报价：24 小时首响 + 差异化模板', min: 30 },
          { no: '4-7', title: '顶展 / 黄金展位 / 超级曝光工具组合投放', min: 30 },
          { no: '4-8', title: '橱窗 + 星等级 + 信保维护年度节奏', min: 25 },
        ],
        homework: [
          '用数据纵横产出 100 词行业词库并分级',
          '重写 10 个主推产品详情页（FABE + 短视频）',
          '搭建 P4P 三级计划并跑 3 天优化否词',
          '完成 15 条 RFQ 精准报价并跟进',
          '输出店铺健康度周报 + 下周优化 action list',
        ],
        deliverable: '曝光环比 +30%、点击率 ≥3%、询盘 ≥15 条、P4P ROI ≥1.5',
      },
      {
        w: 'Week 5',
        theme: '独立站建设与 Google SEO 起量',
        tasks: ['报价策略实战','角色扮演谈判','国别话术差异','客户来访 SOP'],
        lessons: [
          { no: '5-1', title: 'WordPress vs Shopify 选型与主机 / CDN 配置', min: 40 },
          { no: '5-2', title: '独立站信息架构：首页 / 品类 / 产品 / 博客 / 落地页', min: 35 },
          { no: '5-3', title: 'Ahrefs + SEMrush 关键词金字塔搭建实操', min: 40 },
          { no: '5-4', title: 'On-Page SEO：TDK / H1 / Alt / 内链 / Schema 标记', min: 35 },
          { no: '5-5', title: '内容集群与 Topic Cluster 主题聚合页', min: 30 },
          { no: '5-6', title: '外链建设：Guest Post / HARO / 资源页 / Skyscraper', min: 35 },
          { no: '5-7', title: 'Google Search Console + GA4 数据看板搭建', min: 30 },
          { no: '5-8', title: 'Core Web Vitals 与图片 / JS 性能优化', min: 30 },
        ],
        homework: [
          '上线独立站 MVP（≥20 个 SKU + 3 篇博客）',
          '完成 500 词的关键词金字塔并对应落地页',
          '为核心 10 页做完整 On-Page SEO 优化',
          '获取 ≥10 条 DR30+ 外链（客座 / 资源页）',
          '配置 GSC + GA4 并输出首份 SEO 周报',
        ],
        deliverable: '站点 PageSpeed ≥85、收录率 ≥90%、核心词进入 Top50、独立站询盘 ≥3 条',
      },
      {
        w: 'Week 6',
        theme: '商务谈判与跨文化沟通实战',
        tasks: ['验厂 checklist','验货实操','单证与报关','退税与保险'],
        lessons: [
          { no: '6-1', title: 'BATNA / ZOPA / 锚定效应三大谈判理论落地', min: 35 },
          { no: '6-2', title: '报价策略：三档报价 + 条件交换矩阵', min: 35 },
          { no: '6-3', title: '十大降价话术剧本 + 让步节奏控制', min: 40 },
          { no: '6-4', title: 'Hofstede 文化维度：美 / 欧 / 中东 / 东南亚风格', min: 35 },
          { no: '6-5', title: '邮件谈判 10 大高频场景模板库', min: 30 },
          { no: '6-6', title: '电话 / 视频会议破冰与议题主导技巧', min: 30 },
          { no: '6-7', title: '客户接待 5 天 SOP：机场 → 工厂 → 餐叙 → 送别', min: 35 },
          { no: '6-8', title: '展会前中后 SOP + 名片 24 小时跟进法', min: 30 },
        ],
        homework: [
          '针对 3 个真实客户设计三档报价与降价预案',
          '录制并复盘 1 次模拟谈判视频（角色扮演）',
          '输出 10 场景邮件谈判模板库（中英双语）',
          '编写工厂接待 5 天动线 + 议程 + FAQ 文档',
          '完成一次真实客户视频会议并输出会议纪要',
        ],
        deliverable: '报价胜出率 ≥25%、平均降幅 ≤5%、客户满意度 NPS ≥8、模拟谈判评分 ≥85',
      },
      {
        w: 'Week 7',
        theme: '供应链、物流与外贸单证闭环',
        tasks: ['合同审查练习','L/C 审证','认证要求速查','汇率对冲'],
        lessons: [
          { no: '7-1', title: '供应商开发与三级分层管理办法', min: 35 },
          { no: '7-2', title: 'AQL 抽样标准：2.5 / 4.0 与主要 / 次要缺陷判定', min: 35 },
          { no: '7-3', title: 'Incoterms 2020 十一术语与责任风险划分', min: 40 },
          { no: '7-4', title: 'FOB / CIF / DDP 报价成本表逐项拆解', min: 35 },
          { no: '7-5', title: '海运 / 空运 / 铁运选型与运费议价技巧', min: 30 },
          { no: '7-6', title: '报关单证：发票 / 箱单 / 提单 / 产地证 / 形发', min: 35 },
          { no: '7-7', title: '出口退税：单证备案 + 函调 + 电子税局操作', min: 30 },
          { no: '7-8', title: '货运保险 ICC(A/B/C) 与索赔全流程', min: 30 },
        ],
        homework: [
          '完成 3 家供应商实地 / 远程验厂报告',
          '搭建 FOB / CIF / DDP 三合一报价成本模板',
          '模拟一整套出口单证（发票 + 箱单 + 提单 + CO）',
          '跑通一次出口退税模拟申报（含函调应对）',
          '输出物流选型对比表与保险方案建议书',
        ],
        deliverable: '供应商合格率 ≥90%、报价误差 ≤2%、单证一次通过率 100%、退税模拟通过',
      },
      {
        w: 'Week 8',
        theme: '风险管理、合规认证与结业实战',
        tasks: ['案例大赛','导师点评','成长报告','L3 路径规划'],
        lessons: [
          { no: '8-1', title: 'UCP600 信用证 5C 审证清单与软条款识别', min: 40 },
          { no: '8-2', title: '改证函 / 不符点应对 / 交单议付实操', min: 35 },
          { no: '8-3', title: '认证矩阵：CE / FDA / REACH / RoHS / CPSIA 映射', min: 35 },
          { no: '8-4', title: '客户 KYC 与邓白氏 D-U-N-S 信用调查', min: 30 },
          { no: '8-5', title: '汇率对冲：远期结售汇 / 期权 / NDF 场景选择', min: 35 },
          { no: '8-6', title: '反倾销 / 301 / OFAC 制裁清单合规红线', min: 30 },
          { no: '8-7', title: '全流程沙盘：从询盘到收汇 21 节点闭环', min: 40 },
          { no: '8-8', title: '结业答辩 + 个人成长营 90 天行动计划', min: 30 },
        ],
        homework: [
          '完成一份 L/C 审证报告并出改证函',
          '为主推产品输出目标国合规认证地图',
          '撰写 3 家重点客户的 KYC + 信用调查报告',
          '设计本季度汇率对冲方案（含锁汇比例）',
          '结业沙盘：独立完成一单模拟出口全流程并答辩',
        ],
        deliverable: 'L/C 审证准确率 100%、认证地图通过评审、结业答辩评分 ≥85、90 天行动计划落地可执行',
      },
    ],
    tools: ['OKKI 小满','腾道海关数据','LinkedIn Sales Nav','Ahrefs','SEMrush','Shopify','Mailchimp','HubSpot CRM'],
    graduation: {
      hard: [
        '独立站上线（≥20 SKU + 3 篇 SEO 博客），核心词进入 Top50',
        '开发信打开率 ≥40%、回复率 ≥8%、月均有效约会 ≥3',
        '阿里国际站曝光环比 +30%、P4P ROI ≥1.5',
        'L/C 审证 + 3 家客户 KYC 报告通过评审',
        '结业沙盘评分 ≥85 分',
      ],
      soft: [
        '独立主导 1 家 KA 客户从开发到复购',
        '能带 1 位新人（讲解 8 场景邮件模板 + 客户开发方法）',
        '能对导师提出的谈判剧本给出 3 版差异化方案',
        '产出个人 90 天行动计划并每周执行复盘',
      ],
    },
    faq: [
      { q: '我该主攻平台还是独立站？', a: '如果你在工厂 / 贸易公司：平台 + 独立站并行，平台快速出单、独立站长期积累。如果你是 SOHO：独立站 + LinkedIn + 开发信，因为平台年费门槛高。' },
      { q: '开发信回复率一直低于 1%，怎么提升？', a: '90% 的开发信问题不在文案，在于「发给不对的人」。先花时间做 ICP（理想客户画像），用 LinkedIn 精准定位到采购决策人，再用 3 段式邮件（Value → Proof → Ask），回复率至少翻 3 倍。' },
      { q: '独立站要不要投 Google Ads？', a: '独立站上线 3-6 个月内不建议大额投 Ads，先把 SEO 基础和落地页转化做扎实。Ads 只投高购买意图长尾词，日预算 20-50 美金测试转化，再放量。' },
      { q: '客户要求账期怎么办？', a: '账期是把双刃剑。给账期 = 客户忠诚度 + 订单量提升，但也是资金链风险。原则：新客户不给账期，老客户配合中信保 / XTransfer 信保工具再谈。' },
    ],
    sources: ['料神米课','Mr.Hua 米课','阿里国际站直通车官方课','Ahrefs / SEMrush 中文文档','Shopify / WordPress 建站教程','OKKI 小满','UCP600 信用证统一惯例','外汇局汇率避险指南'],
  },

  l3: {
    id: 'l3',
    tier: 'LEVEL 03',
    title: '高手跃迁塔',
    subtitle: '做上去',
    tag: '2 年以上 / 团队 / 创业',
    accentHex: '#d4af37',
    accentSoft: 'rgba(212, 175, 55, 0.14)',
    accentSoftStrong: 'rgba(212, 175, 55, 0.25)',
    stat: { modules: 7, hours: 72, lessons: 96 },
    description: '从执行者变成经营者。你不再是「完成任务」，而是设计商业系统：战略选品、大客户经营、品牌出海、团队搭建、资本运作。',
    outcome: '12 周产出一份包含选品分析 / 市场策略 / 团队规划 / 财务预测的完整商业计划书。',
    pedagogy: 'Jobs-to-be-Done + SPIN 深度销售 + OGSM 战略解码 + 第二曲线创新',
    modules: [
      {
        name: '战略选品与市场洞察',
        desc: '选对赛道比努力重要',
        points: ['四维评估选品模型（容量 / 竞争 / 利润 / 壁垒）','行业研究框架（宏观 / 竞争 / 需求 / 技术）','数据驱动选品（海关数据 / Trends / Amazon BSR）','蓝海市场发现方法','竞品情报体系构建'],
        methodology: [
          '四维选品评估：需求容量 × 竞争密度 × 毛利结构 × 合规壁垒',
          '数据驱动选品：海关 + Google Trends + FastMoss 三源交叉',
          '蓝海发现：波特五力 + Blue Ocean ERRC 找价值曲线断点',
          '竞品情报体系：Top10 SKU 反拆价盘 / 词盘 / 专利 / 认证',
          'Jobs-to-be-Done 需求穿透：从功能到情感 / 社会诉求',
        ],
        steps: [
          '建立自有品类雷达（HS 编码 + 目的国 + 海关数据订阅）',
          '搭建 20 家标杆竞品档案库，季度刷新一次',
          '用四维评分卡对现有 SKU 做 ABCD 汰换分级',
          '锁定 2-3 个蓝海细分场景做 MVP 打样测试',
          '3 个月内完成新品从选品到首单闭环 KPI 复盘',
        ],
      },
      {
        name: '大客户战略经营 (KAM)',
        desc: '一个 KA 顶一百个散客',
        points: ['KA 识别与分级体系','SPIN 深度需求挖掘','解决方案式销售（卖方案而非产品）','年度 Account Plan 制定','NPS 客户满意度体系','CEO-to-CEO 高层关系维护'],
        methodology: [
          'KA 三级分层：战略型 SKA / 增长型 KA / 潜力型 EKA',
          'SPIN 深度销售：Situation-Problem-Implication-Need Payoff',
          'Account Plan 年度经营：White Space + Share of Wallet',
          'CEO-CEO 关系工程：多线程 Buying Center 关系地图',
          '客户价值方程：为 KA 创造 3-5 倍供应商切换成本',
        ],
        steps: [
          '20 / 80 盘点客户，锁定 Top10 战略客户',
          '为每个 SKA 建立客户档案（组织架构 + 决策链）',
          '一年 4 次现场拜访 + CEO 层战略年会机制',
          '交付一份完整 Account Plan（含 White Space）',
          '季度经营复盘，KA 收入占比目标 60%+',
          '与 Top3 客户签订 JBP 联合生意计划',
        ],
      },
      {
        name: '品牌出海与内容营销',
        desc: 'OEM → ODM → OBM 升级',
        points: ['品牌化战略与价值主张','行业白皮书 / 视频 / Podcast / Webinar','LinkedIn Thought Leadership','海外 PR 与媒体关系','客户证言与 Case Study','Referral Program 口碑营销'],
        methodology: [
          'OEM → ODM → OBM 三级跃迁与利润跃升模型',
          'LinkedIn Thought Leadership：CEO 个人 IP × 公司页矩阵',
          '内容金字塔：白皮书 / Case Study / 短视频 / UGC 四层',
          'STP + 定位屋：Segment / Target / Positioning / 价值主张',
          '全域 Owned + Earned + Paid 媒介组合与归因模型',
        ],
        steps: [
          '完成品牌资产盘点与海外商标 / 域名注册布局',
          '产出年度品牌白皮书 1 份 + Case Study 6 篇',
          '搭建 EN 独立站 + SEO 内容中枢（月更 8 篇）',
          'CEO / 核心销售 LinkedIn 日更 + 行业展会演讲',
          '投放 LinkedIn / Google 精准 ABM 广告并追踪 MQL',
          '一年内实现自然流量询盘占比 30%+',
        ],
      },
      {
        name: '团队管理与体系搭建',
        desc: '让业务不再依赖你',
        points: ['组织架构三种模式（按市场 / 产品 / 职能）','人才选拔面试评估标准','绩效激励设计（底薪 + 提成 + 奖金模型）','SOP 手册与业务流程标准化','客户资源公司化 + 离职风险管理','跨时区远程团队协作'],
        methodology: [
          '铁三角组织：销售 + 产品 + 客服围绕 KA 端到端负责',
          '招聘四维 MAP-P：动机 / 能力 / 价值观 / 潜力',
          'PBC + 分润制：底薪 + 提成 + 利润分红 + 项目跟投',
          'SOP 沉淀：从询盘到收款 12 环节标准动作可视化',
          'OKR / OGSM 双周会：战略解码到个人季度目标',
        ],
        steps: [
          '设计公司组织架构 2.0（前中后台分工）',
          '完成岗位说明书 + 胜任力模型 + 薪酬带宽',
          '搭建 SOP 手册 + Notion / 飞书知识库',
          '建立 361 绩效 + 季度校准会议机制',
          '培养 2-3 名业务合伙人（干股或跟投）',
          '远程 / 多城协作：日站会 + 周复盘 + 月经营会',
        ],
      },
      {
        name: '财务与利润管理',
        desc: '把生意从模糊变成清晰',
        points: ['全成本核算模型（含隐藏成本）','成本 / 市场 / 价值三种定价策略','现金流与应收账款管理','出口退税优化 + 离岸架构','转让定价合规','SOHO 财务规划'],
        methodology: [
          '全成本核算：BOM + 关税 + 汇率 + 资金 + 摊销一图看全',
          '价值定价：Value-based Pricing 替代 Cost-plus',
          '现金流三张表：经营 + 投资 + 筹资滚动 13 周预测',
          '离岸架构：内地 → 香港 → BVI → 目的国四层合规',
          '转让定价：OECD 独立交易原则 + 功能风险资产分析',
        ],
        steps: [
          '搭建产品级 P&L，识别真实毛利前 20% SKU',
          '制定分市场 / 分客户差异化价格阶梯',
          '建立 13 周现金流预测表并每周滚动更新',
          '与税务 / 律所设计香港 + 境内公司架构',
          '完成转让定价同期资料及利润切分政策',
          '年度审计 + ROIC / ROE 经营健康度诊断',
        ],
      },
      {
        name: '供应链战略',
        desc: '从单一供应商到供应链生态',
        points: ['供应链整合与生态构建','多品类经营策略取舍','海外仓选址与运营','ERP 系统选型与实施','供应链数字化 / 可视化','备选供应商 + 地缘政治对冲'],
        methodology: [
          '供应链生态：核心 + 备胎 + 海外产能三级布局',
          '海外仓 3.0：前置仓 + FBA + 第三方海外仓组合',
          'ERP 数字底座：订单-采购-物流-资金-BI 一体化',
          '地缘政治对冲：+1 战略（越南 / 墨西哥 / 摩洛哥）',
          'S&OP 销售与运营协同：需求预测 → 产能计划月度对齐',
        ],
        steps: [
          '绘制端到端供应链地图与关键卡点识别',
          '建立主供 + 备供 + 海外供 3 家供应商矩阵',
          '上线 ERP + WMS + BI 系统',
          '布局 1-2 个战略市场海外仓（美 / 欧 / 东南亚）',
          '制定关税 / 汇率 / 合规三类地缘风险预案',
          'S&OP 月度会议机制，库存周转提升 30%',
        ],
      },
      {
        name: '创业与商业模式',
        desc: '把外贸做成事业而非工作',
        points: ['SOHO 从 0 到 1 完整 checklist','外贸公司注册 / 开户 / 资质 / 团队','四种商业模式：贸易 / 工贸 / 品牌 / 平台','融资估值 + 股权设计','AI 工具全流程应用','数字化转型路径'],
        methodology: [
          'SOHO 0 → 1 三阶段：单点突破 → 产品化 → 组织化',
          '商业模式画布 BMC + 第二曲线创新组合',
          '融资估值：DCF + 可比公司 + PSR，讲好增长故事',
          'AI 全流程武装：选品-开发-写单-客服-数据五段',
          '数字化转型三步：数据在线 → 流程在线 → 决策在线',
        ],
        steps: [
          '明确细分市场 + 差异化定位 + MVP 验证闭环',
          '完成公司三年战略 OGSM 与年度经营预算',
          '搭建 AI Agent 工作流（GPT + RPA + ERP）',
          '跑通 1-2 条第二曲线（品类 / 渠道 / 模式）',
          '完成天使 / A 轮融资 BP + 估值建模',
          '建立董事会 / 顾问团 + 期权池长期治理机制',
        ],
      },
    ],
    weeks: [
      {
        w: 'Week 1-2',
        theme: '战略选品与市场洞察 —— 从跟单员到品类操盘手',
        tasks: ['选品四维评估','行业研究报告','蓝海机会识别','竞品情报系统'],
        lessons: [
          { no: 'W1-2·1', title: '用 Jobs-to-be-Done 框架拆解客户真实需求与场景', min: 40 },
          { no: 'W1-2·2', title: '四维选品评估卡：需求 × 竞争 × 毛利 × 合规实战演练', min: 45 },
          { no: 'W1-2·3', title: '海关数据 + Google Trends + FastMoss 三源交叉验证工作坊', min: 40 },
          { no: 'W1-2·4', title: '波特五力 & Blue Ocean ERRC 找价值曲线断点', min: 40 },
          { no: 'W1-2·5', title: '构建 20 家竞品档案库：价盘 / 词盘 / 专利 / 认证反拆', min: 40 },
          { no: 'W1-2·6', title: '从选品到 MVP 打样：72 小时快速验证 SOP', min: 35 },
          { no: 'W1-2·7', title: 'AI 选品：ChatGPT + Helium10 + Sellersprite 组合拳', min: 40 },
        ],
        homework: [
          '输出一份完整《四维选品评估报告》覆盖 5 款 SKU',
          '建立 20 家竞品档案库（含价盘、评论、词盘）',
          '提交一份《目的国市场蓝海机会报告》',
          '对现有 SKU 做 ABCD 汰换分级并给出增删清单',
        ],
        deliverable: '交付物：品类雷达 v1.0 + 竞品档案库 + 蓝海机会报告；识别 2 个以上蓝海机会点、SKU 汰换率 ≥20%',
      },
      {
        w: 'Week 3-4',
        theme: '大客户战略经营 KAM —— 从询盘业务员到 KA 操盘手',
        tasks: ['KA 分级','SPIN 演练','Account Plan','高层关系'],
        lessons: [
          { no: 'W3-4·1', title: 'KA 三级分层模型：SKA / KA / EKA 客户资产盘点', min: 40 },
          { no: 'W3-4·2', title: 'SPIN 深度销售在展会现场与视频会议中的落地话术', min: 45 },
          { no: 'W3-4·3', title: '客户 Buying Center 决策链解剖：EB / UB / TB / Coach', min: 40 },
          { no: 'W3-4·4', title: '料神米课 KA 开发信 & 二次跟进 8 步节奏', min: 40 },
          { no: 'W3-4·5', title: 'Account Plan 年度经营：White Space & Share of Wallet 计算', min: 45 },
          { no: 'W3-4·6', title: 'CEO-CEO 关系工程：如何策划一场高质量的高层拜访', min: 35 },
          { no: 'W3-4·7', title: 'JBP 联合生意计划谈判要点与合同条款设计', min: 40 },
          { no: 'W3-4·8', title: '季度客户经营复盘会议模板', min: 30 },
        ],
        homework: [
          '输出一份完整 Account Plan（含 White Space 与年度增量目标）',
          '为 Top3 客户绘制 Buying Center 关系地图',
          '撰写一封 SPIN 结构化开发信 + 3 轮跟进邮件',
          '设计一份 JBP 联合生意计划提案 PPT',
          '完成 Top10 KA 客户资产盘点表',
        ],
        deliverable: '交付物：Top10 KA 客户档案 + 3 份 Account Plan + JBP 提案；季度内新增高层拜访 5 次、KA 询盘转化率提升 30%',
      },
      {
        w: 'Week 5-6',
        theme: '品牌出海与内容营销 —— 从卖货到造牌',
        tasks: ['品牌定位','白皮书写作','LinkedIn IP','Case Study'],
        lessons: [
          { no: 'W5-6·1', title: 'OEM → ODM → OBM 三级跃迁：利润与风险跃升模型', min: 40 },
          { no: 'W5-6·2', title: 'STP + 定位屋：为你的品牌写一句 12 字 Slogan', min: 35 },
          { no: 'W5-6·3', title: 'LinkedIn Thought Leadership：CEO 个人 IP 30 天冷启动', min: 40 },
          { no: 'W5-6·4', title: '白皮书写作：从行业趋势到解决方案叙事结构', min: 45 },
          { no: 'W5-6·5', title: 'Case Study 六段式：Challenge-Solution-Result-Insight', min: 40 },
          { no: 'W5-6·6', title: '独立站 SEO 内容中枢：Topic Cluster + E-E-A-T 构建', min: 40 },
          { no: 'W5-6·7', title: '海外展会 Pitch：3 分钟讲清品牌故事', min: 35 },
          { no: 'W5-6·8', title: 'ABM 广告投放：LinkedIn + Google 精准触达决策人', min: 40 },
        ],
        homework: [
          '输出一份 5000 字行业白皮书 + 2 篇 Case Study',
          '为公司 / CEO 完成 LinkedIn 主页改造并连续日更 14 天',
          '撰写品牌定位屋（Target / Insight / RTB / Slogan）',
          '策划一场海外线上发布会 / Webinar 完整方案',
          '提交独立站 SEO 内容日历（3 个月 24 篇选题）',
        ],
        deliverable: '交付物：白皮书 1 份 + Case Study 2 篇 + 品牌定位屋 + SEO 内容日历；LinkedIn 粉丝增长 500+、白皮书下载 100+',
      },
      {
        w: 'Week 7-8',
        theme: '团队管理与体系搭建 —— 从个人英雄到组织复利',
        tasks: ['组织架构','招聘评估','绩效模型','SOP 手册'],
        lessons: [
          { no: 'W7-8·1', title: '从业务员到总经理的思维升级：从做业务到做组织', min: 40 },
          { no: 'W7-8·2', title: '外贸公司组织架构 2.0：前中后台与铁三角设计', min: 40 },
          { no: 'W7-8·3', title: '招聘四维 MAP-P 模型与结构化面试话术', min: 40 },
          { no: 'W7-8·4', title: 'PBC + 分润制薪酬包设计：底薪 / 提成 / 分红 / 跟投', min: 45 },
          { no: 'W7-8·5', title: 'SOP 沉淀：从询盘到收款 12 环节可视化', min: 40 },
          { no: 'W7-8·6', title: 'OKR / OGSM 战略解码工作坊：从公司到个人', min: 45 },
          { no: 'W7-8·7', title: '远程 / 多城协作节奏与知识管理体系（飞书 / Notion）', min: 35 },
          { no: 'W7-8·8', title: '文化仪式设计：从周会 / 月经营会到年会', min: 30 },
        ],
        homework: [
          '设计公司三年战略 OGSM 表格并完成年度解码',
          '输出组织架构图 2.0 + 关键岗位说明书 3 份',
          '编写核心业务 SOP 手册（不少于 20 个流程节点）',
          '设计 2026 年薪酬激励方案（含分润 / 跟投细则）',
          '完成一次团队季度经营复盘会（附会议纪要）',
        ],
        deliverable: '交付物：OGSM 战略表 + 组织架构 + SOP 手册 + 薪酬方案；核心岗位到位率 100%、人均产值 +20%、SOP 覆盖率 ≥80%',
      },
      {
        w: 'Week 9-10',
        theme: '财务、供应链与全球化架构 —— 从算账到经营',
        tasks: ['全成本核算','离岸架构','海外仓规划','ERP 选型'],
        lessons: [
          { no: 'W9-10·1', title: '读懂三张表：外贸老板必备的经营仪表盘', min: 40 },
          { no: 'W9-10·2', title: '产品级 P&L 与全成本核算实战（BOM + 关税 + 汇率 + 资金）', min: 45 },
          { no: 'W9-10·3', title: 'Value-based Pricing：为品牌溢价定价', min: 40 },
          { no: 'W9-10·4', title: '13 周滚动现金流预测模型 Excel 实操', min: 40 },
          { no: 'W9-10·5', title: '香港-BVI-境内公司离岸架构与合规红线', min: 40 },
          { no: 'W9-10·6', title: 'OECD 转让定价与功能风险资产分析入门', min: 40 },
          { no: 'W9-10·7', title: '海外仓 3.0 与 S&OP 销售运营协同月度会', min: 40 },
          { no: 'W9-10·8', title: '地缘政治对冲：中国+1（越南 / 墨西哥）战略落地', min: 35 },
          { no: 'W9-10·9', title: 'ERP + WMS + BI 数字底座选型与实施路线图', min: 35 },
        ],
        homework: [
          '搭建产品级 P&L 表并识别毛利前 20% SKU 清单',
          '输出一份 13 周滚动现金流预测模型',
          '设计公司离岸架构方案（含税负测算与合规评估）',
          '绘制供应链端到端地图并识别 5 个卡点',
          '制定海外仓 / 中国+1 布局提案（含投资回收测算）',
        ],
        deliverable: '交付物：产品级 P&L + 现金流预测 + 离岸架构方案 + 供应链地图；识别毛利改善 3 个百分点空间、库存周转 +20%',
      },
      {
        w: 'Week 11-12',
        theme: '创业与商业模式跃迁 —— 从 CEO 到 Founder',
        tasks: ['商业模式设计','融资估值','商业计划书','路演演练'],
        lessons: [
          { no: 'W11-12·1', title: 'SOHO 0 → 1 三阶段路径：从单点突破到组织化', min: 40 },
          { no: 'W11-12·2', title: '商业模式画布 BMC 深度打磨与九宫格审视', min: 40 },
          { no: 'W11-12·3', title: '第二曲线创新：从既有业务里长出新增长引擎', min: 40 },
          { no: 'W11-12·4', title: 'AI 全流程武装：选品-开发-写单-客服-数据 5 段 Agent', min: 45 },
          { no: 'W11-12·5', title: '融资估值实战：DCF + 可比公司 + PSR 三种方法', min: 45 },
          { no: 'W11-12·6', title: '投资人 BP 写作与路演：15 张 PPT 讲清你的故事', min: 40 },
          { no: 'W11-12·7', title: '公司治理与股权设计：期权池 / AB 股 / 董事会', min: 40 },
          { no: 'W11-12·8', title: '个人跃迁：CEO 时间管理与年度学习体系', min: 30 },
          { no: 'W11-12·9', title: '毕业设计路演：三年战略与融资 BP 现场答辩', min: 60 },
        ],
        homework: [
          '输出公司 BMC 画布 + 三年第二曲线路线图',
          '完成一份完整融资 BP（15 页）+ 估值模型 Excel',
          '设计 AI Agent 工作流并跑通 1 条业务链路',
          '提交个人未来 3 年高手跃迁计划书（含年度 OKR）',
          '参加毕业路演，向导师团进行 20 分钟战略答辩',
        ],
        deliverable: '交付物：BMC 画布 + 融资 BP + AI 工作流 Demo + 个人跃迁计划 + 毕业路演；BP 通过率、AI 工作流跑通、路演综合评分 ≥85 分',
      },
    ],
    tools: ['Ahrefs Pro','Salesforce','HubSpot Enterprise','NetSuite ERP','Notion','Airtable','ChatGPT Pro','Claude Pro'],
    graduation: {
      levels: [
        'Trader（青铜）：完成 M1+M2 模块，独立操盘 KA 客户',
        'Manager（白银）：完成 M3+M4 模块，带 5-10 人团队',
        'General Manager（黄金）：完成 M5+M6 模块，掌管 P&L',
        'Founder（王者）：完成 M7 模块，具备融资与商业模式设计能力',
      ],
      criteria: '12 周内交付 ≥25 份作业、6 份关键交付物，累计学习时长 ≥120 小时，毕业路演综合评分 ≥85 分方可颁发《外贸高手跃迁认证》',
    },
    faq: [
      { q: '一个人 SOHO 能做多大？', a: '天花板在 300-500 万美金营收。再往上必须搭团队。这个阶段最重要的不是勤奋，是判断力：选什么品、进什么市场、押哪个客户，一个决策错了半年白干。' },
      { q: '要不要做自己的品牌？', a: '如果你的产品差异化足够（专利 / 设计 / 工艺），或者目标市场有品牌溢价空间（欧美 B2C），值得做。如果只是 me-too 产品打价格战，做品牌只会烧钱。判断标准：能不能讲出一个客户愿意付溢价的故事。' },
      { q: '团队怎么设计激励机制？', a: '外贸团队最常见的坑是「高提成低底薪」，导致业务员只做眼前订单不做长期客户经营。推荐结构：底薪覆盖基本生活 + 阶梯提成 + 老客户复购年度奖金 + 新市场开拓专项奖金。' },
      { q: 'AI 会取代外贸业务员吗？', a: '会取代「只会翻译邮件、只会填 PI」的初级业务员，但会大幅赋能懂客户懂产品懂谈判的资深业务员。你的护城河从「英语好 + 沟通勤快」变成「行业认知深 + 关系资产厚」。现在开始训练自己用 AI 做研究、做谈判剧本、做客户档案。' },
    ],
    sources: ['料神米课 KA 大客户课','Mr.Hua 米课高阶课','阿里国际站 KA 成长阵地','LinkedIn 中国 B2B 品牌白皮书','连连国际品牌出海白皮书','HBR《Key Account Management》','OECD 转让定价指南','北森 OGSM 战略解码','混沌大学第二曲线'],
  },
};

/* ---------- Icons ---------- */
window.SharedIcon = null;

/* Global CSS helpers appended to <head> */
(function injectSharedStyles() {
  const style = document.createElement('style');
  style.textContent = `
    html { scroll-behavior: smooth; }
    body { font-family: 'Inter','PingFang SC','Microsoft YaHei',sans-serif; background:#050a14; color:#f4f1e8; -webkit-font-smoothing: antialiased; }
    .font-display { font-family: 'Noto Serif SC', serif; letter-spacing: -0.01em; }
    .gold-text {
      background: linear-gradient(135deg, #d4af37 0%, #f6ecc5 45%, #d4af37 90%);
      -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; color: transparent;
      background-size: 200% 100%; animation: shimmer 6s linear infinite;
    }
    .grid-lines {
      background-image:
        linear-gradient(rgba(212,175,55,0.06) 1px, transparent 1px),
        linear-gradient(90deg, rgba(212,175,55,0.06) 1px, transparent 1px);
      background-size: 60px 60px;
    }
    .divider-gold { background: linear-gradient(90deg, transparent, #d4af37, transparent); height:1px; }
    .card-glow { position:relative; }
    .card-glow::before {
      content:''; position:absolute; inset:-1px; border-radius:inherit; padding:1px;
      background: linear-gradient(135deg, rgba(212,175,55,0.5), rgba(212,175,55,0), rgba(212,175,55,0.3));
      -webkit-mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0);
      -webkit-mask-composite: xor; mask-composite: exclude; pointer-events:none;
    }
    .stat-num { font-variant-numeric: tabular-nums; }
    ::selection { background: rgba(212,175,55,0.4); color: #faf9f5; }
  `;
  document.head.appendChild(style);
})();
